[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
auto_detect_solc = true
optimizer = true
optimizer_runs = 800
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
evm_version = "cancun"
ffi = true
fs_permissions = [
  { access = "read-write", path = "./" }
]
gas_reports = ["*"]
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std-master/src/",
  "@uniswap/v3-core/=lib/v3-core-main/",
  "@uniswap/v3-periphery/=lib/v3-periphery-main/",
  "v3-core/=lib/v3-core-main/contracts/",
  "v3-periphery/=lib/v3-periphery-main/contracts/"
]
